workflows:
  ios-workflow:
    name: Rehberler iOS Workflow
    environment:
      vars:
        BUNDLE_ID: "turkiye.turistrehberleri.com"
        APP_STORE_APPLE_ID: "6746189878"
      xcode: latest
    scripts:
      - name: Set up keychain to be used for code signing using Codemagic CLI
        script: |
          keychain initialize

      - name: Fetch signing files from App Store Connect
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID"             --type IOS_APP_STORE             --create

      - name: Set up signing certificate
        script: |
          keychain add-certificates

      - name: Set code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Build IPA for distribution
        script: |
          xcode-project build-ipa             --project "SngineWeb.xcodeproj"             --scheme "SngineWeb"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true