workflows:
  ios-workflow:
    name: Rehberler iOS Workflow
    environment:
      vars:
        BUNDLE_ID: "turkiye.turistrehberleri.com"
        APP_STORE_APPLE_ID: "6746189878"
      xcode: latest

    scripts:
      - name: Set up keychain
        script: |
          keychain initialize

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create

      - name: Add signing certificate
        script: |
          keychain add-certificates

      - name: Set Xcode signing
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "SngineWeb.xcodeproj" \
            --scheme "SngineWeb"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        name: "Dil Maratonu"
        submit_to_testflight: true
