workflows:

  ios-workflow:

    name: iOS Workflow

    integrations:
      app_store_connect: Dil Maratonu

    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "SngineWeb.xcodeproj"
        XCODE_SCHEME: "SngineWeb"
        BUNDLE_ID: "turkiye.turistrehberleri.com"
        APP_STORE_APPLE_ID: 6746189878
      secure:
        APP_STORE_CONNECT_ISSUER_ID: EncryptedValueHere
        APP_STORE_CONNECT_KEY_IDENTIFIER: EncryptedValueHere
        APP_STORE_CONNECT_PRIVATE_KEY: EncryptedValueHere

    scripts:
      - name: Increment build number
        script: | 
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))

      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE
          xcode-project use-profiles

      - name: Build ipa for distribution
        script: | 
          xcode-project build-archive \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

          xcode-project export-ipa

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_identifier: $APP_STORE_CONNECT_KEY_IDENTIFIER
        private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        app_id: $APP_STORE_APPLE_ID
