workflows:

  ios-workflow:

    name: iOS Workflow

    integrations:

      app_store_connect: Dil Maratonu

    environment:

      vars:

        APP_STORE_APPLE_ID: 6746189878

    scripts:

      - name: Increment build number

        script: | 

          #!/bin/sh

          cd $CM_BUILD_DIR

          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")

          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))

      - name: Build ipa for distribution

      script: | 

        # build command